# Generated by Django 3.0.5 on 2020-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('cardnum', models.CharField(max_length=16)),
                ('cvc', models.CharField(max_length=3)),
                ('cardvalid', models.CharField(max_length=4)),
                ('money', models.CharField(max_length=100)),
            ],
        ),
    ]
