# Generated by Django 3.0.5 on 2020-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paydata',
            name='cardvalid',
            field=models.CharField(max_length=6),
        ),
    ]
